version: '3'

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: library/mongo:4.2
    environment:
      - MONGO_INITDB_DATABASE=base
    volumes:
      - .db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    expose:
      - 27017
    command: mongod

  server:
    build: .
    container_name: server
    command: ./entrypoint.sh
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    ports:
      - "80:80"
    expose:
      - 80