version: '3'

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: library/mongo:4.2
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - .db:/docker-entrypoint-initdb.d
    expose:
      - 27017
    command: mongod

  server:
    build: .
    container_name: server
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    ports:
      - "80:80"
    expose:
      - 80